spring.datasource.url=${URL_DESPESA}
spring.datasource.username=${USER_DESPESA}
spring.datasource.password=${PASSWORD_DESPESA}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.converters.preferred-json-mapper=jackson

jwt.secret=4f616d7a426e5a32536b4b4150516d4742686b4d313233414243444546474849

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true