spring.datasource.url=${URL_DESPESA}
spring.datasource.username=${USER_DESPESA}
spring.datasource.password=${PASSWORD_DESPESA}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.converters.preferred-json-mapper=jackson

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true